### ISSUE TITLE
Type "CL_ABAP_CONV_CODEPAGE" is unknown on SAP ERP 6.0 EHP8 / SAP_BASIS/SAP_ABA 7.50 SP 17

### ISSUE THREAD

**Issue by gregorwolf** [open-abap/open-table-maintenance#14]
Hi @larshp,

I've just tried to activate the class ZCL_OTM_TABLE_MAINTENANCE on the following system:

- SAP ERP 6.0 EHP8 
- SAP_BASIS/SAP_ABA 7.50 SP 17

but it fails with the error that:

> Type "CL_ABAP_CONV_CODEPAGE" is unknown 

I can only find this CL_ABAP_CONV* classes:

- CL_ABAP_CONV_IN_CE
- CL_ABAP_CONV_OBJ
- CL_ABAP_CONV_OUT_CE
- CL_ABAP_CONV_UC_NUMBER
- CL_ABAP_CONV_X2X_CE

**Comment by larshp** [comment]
thanks

argh, will have to do some tricks with dynamic calls

**Comment by larshp** [comment]
and now https://abapedia.org/steampunk-2111-api/cl_abap_conv_codepage.clas.html also shows that the object does not exist on  750

**Comment by larshp** [comment]
@gregorwolf try this branch, https://github.com/open-abap/open-table-maintenance/pull/15

**Comment by gregorwolf** [comment]
Works with the corrections from #15. Thank you.
